export const CountryList = [
  "",
  "CAN",
  "AFG",
  "ALB",
  "ALG",
  "ASA",
  "AND",
  "ANG",
  "ANT",
  "ARG",
  "ARM",
  "ARU",
  "AUS",
  "AUT",
  "AZE",
  "BAH",
  "BRN",
  "BAN",
  "BAR",
  "BLR",
  "BEL",
  "BIZ",
  "BEN",
  "BER",
  "BHU",
  "BOL",
  "BIH",
  "BOT",
  "BRA",
  "IVB",
  "BRU",
  "BUL",
  "BUR",
  "BDI",
  "CAM",
  "CMR",
  "CPV",
  "CAY",
  "CAF",
  "CHA",
  "CHI",
  "CHN",
  "COL",
  "COM",
  "COK",
  "CRC",
  "CIV",
  "CRO",
  "CUB",
  "CYP",
  "CZE",
  "COD",
  "DEN",
  "DJI",
  "DMA",
  "DOM",
  "ECU",
  "EGY",
  "ESA",
  "GEQ",
  "ERI",
  "EST",
  "ETH",
  "FSM",
  "FIJ",
  "FIN",
  "FRA",
  "GAB",
  "GAM",
  "GEO",
  "GER",
  "GHA",
  "GRE",
  "GRN",
  "GUM",
  "GUA",
  "GUI",
  "GBS",
  "GUY",
  "HAI",
  "HON",
  "HKG",
  "HUN",
  "ISL",
  "IND",
  "INA",
  "IRI",
  "IRQ",
  "IRL",
  "ISR",
  "ITA",
  "JAM",
  "JPN",
  "JOR",
  "KAZ",
  "KEN",
  "KIR",
  "KUW",
  "KGZ",
  "LAO",
  "LAT",
  "LIB",
  "LES",
  "LBR",
  "LBA",
  "LIE",
  "LTU",
  "LUX",
  "MKD",
  "MAD",
  "MAW",
  "MAS",
  "MDV",
  "MLI",
  "MLT",
  "MHL",
  "MTN",
  "MRI",
  "MEX",
  "MDA",
  "MON",
  "MGL",
  "MNE",
  "MAR",
  "MOZ",
  "MYA",
  "NAM",
  "NRU",
  "NEP",
  "NED",
  "AHO",
  "NZL",
  "NCA",
  "NIG",
  "NGR",
  "PRK",
  "NOR",
  "OMA",
  "PAK",
  "PLW",
  "PLE",
  "PAN",
  "PNG",
  "PAR",
  "PER",
  "PHI",
  "POL",
  "POR",
  "PUR",
  "QAT",
  "CGO",
  "ROM",
  "RUS",
  "RWA",
  "SKN",
  "LCA",
  "VIN",
  "SAM",
  "SMR",
  "STP",
  "KSA",
  "SEN",
  "SRB",
  "SEY",
  "SLE",
  "SIN",
  "SVK",
  "SLO",
  "SOL",
  "SOM",
  "RSA",
  "KOR",
  "ESP",
  "SRI",
  "SUD",
  "SUR",
  "SWZ",
  "SWE",
  "SUI",
  "SYR",
  "TPE",
  "TJK",
  "TAN",
  "THA",
  "TLS",
  "TOG",
  "TGA",
  "TRI",
  "TUN",
  "TUR",
  "TKM",
  "TUV",
  "UGA",
  "UKR",
  "UAE",
  "GBR",
  "USA",
  "URU",
  "UZB",
  "VAN",
  "VEN",
  "VIE",
  "ISV",
  "YEM",
  "ZAM",
  "ZIM",
] as const;
export const CountryNameList: {
  [countryCode in (typeof CountryList)[number]]: string;
} = {
  "": "Unaffiliated",
  CAN: "Canada",
  AFG: "Afghanistan",
  ALB: "Albania",
  ALG: "Algeria",
  ASA: "American Samoa",
  AND: "Andorra",
  ANG: "Angola",
  ANT: "Antigua and Barbuda",
  ARG: "Argentina",
  ARM: "Armenia",
  ARU: "Aruba",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BAH: "Bahamas",
  BRN: "Bahrain",
  BAN: "Bangladesh",
  BAR: "Barbados",
  BLR: "Belarus",
  BEL: "Belgium",
  BIZ: "Belize",
  BEN: "Benin",
  BER: "Bermuda",
  BHU: "Bhutan",
  BOL: "Bolivia",
  BIH: "Bosnia and Herzegovina",
  BOT: "Botswana",
  BRA: "Brazil",
  IVB: "British Virgin Islands",
  BRU: "Brunei",
  BUL: "Bulgaria",
  BUR: "Burkina Faso",
  BDI: "Burundi",
  CAM: "Cambodia",
  CMR: "Cameroon",
  CPV: "Cape Verde",
  CAY: "Cayman Islands",
  CAF: "Central African Republic",
  CHA: "Chad",
  CHI: "Chile",
  CHN: "China",
  COL: "Colombia",
  COM: "Comoros",
  COK: "Cook Islands",
  CRC: "Costa Rica",
  CIV: "Côte d'Ivoire",
  CRO: "Croatia",
  CUB: "Cuba",
  CYP: "Cyprus",
  CZE: "Czech Republic",
  COD: "Democratic Republic of the Congo",
  DEN: "Denmark",
  DJI: "Djibouti",
  DMA: "Dominica",
  DOM: "Dominican Republic",
  ECU: "Ecuador",
  EGY: "Egypt",
  ESA: "El Salvador",
  GEQ: "Equatorial Guinea",
  ERI: "Eritrea",
  EST: "Estonia",
  ETH: "Ethiopia",
  FSM: "Federated States of Micronesia",
  FIJ: "Fiji",
  FIN: "Finland",
  FRA: "France",
  GAB: "Gabon",
  GAM: "Gambia",
  GEO: "Georgia",
  GER: "Germany",
  GHA: "Ghana",
  GRE: "Greece",
  GRN: "Grenada",
  GUM: "Guam",
  GUA: "Guatemala",
  GUI: "Guinea",
  GBS: "Guinea-Bissau",
  GUY: "Guyana",
  HAI: "Haiti",
  HON: "Honduras",
  HKG: "Hong Kong",
  HUN: "Hungary",
  ISL: "Iceland",
  IND: "India",
  INA: "Indonesia",
  IRI: "Iran",
  IRQ: "Iraq",
  IRL: "Ireland",
  ISR: "Israel",
  ITA: "Italy",
  JAM: "Jamaica",
  JPN: "Japan",
  JOR: "Jordan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KIR: "Kiribati",
  KUW: "Kuwait",
  KGZ: "Kyrgyzstan",
  LAO: "Laos",
  LAT: "Latvia",
  LIB: "Lebanon",
  LES: "Lesotho",
  LBR: "Liberia",
  LBA: "Libya",
  LIE: "Liechtenstein",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MKD: "Macedonia",
  MAD: "Madagascar",
  MAW: "Malawi",
  MAS: "Malaysia",
  MDV: "Maldives",
  MLI: "Mali",
  MLT: "Malta",
  MHL: "Marshall Islands",
  MTN: "Mauritania",
  MRI: "Mauritius",
  MEX: "Mexico",
  MDA: "Moldova",
  MON: "Monaco",
  MGL: "Mongolia",
  MNE: "Montenegro",
  MAR: "Morocco",
  MOZ: "Mozambique",
  MYA: "Myanmar",
  NAM: "Namibia",
  NRU: "Nauru",
  NEP: "Nepal",
  NED: "Netherlands",
  AHO: "Netherlands Antilles",
  NZL: "New Zealand",
  NCA: "Nicaragua",
  NIG: "Niger",
  NGR: "Nigeria",
  PRK: "North Korea",
  NOR: "Norway",
  OMA: "Oman",
  PAK: "Pakistan",
  PLW: "Palau",
  PLE: "Palestine",
  PAN: "Panama",
  PNG: "Papua New Guinea",
  PAR: "Paraguay",
  PER: "Peru",
  PHI: "Philippines",
  POL: "Poland",
  POR: "Portugal",
  PUR: "Puerto Rico",
  QAT: "Qatar",
  CGO: "Republic of the Congo",
  ROM: "Romania",
  RUS: "Russia",
  RWA: "Rwanda",
  SKN: "Saint Kitts and Nevis",
  LCA: "Saint Lucia",
  VIN: "Saint Vincent and the Grenadines",
  SAM: "Samoa",
  SMR: "San Marino",
  STP: "Sao Tome and Principe",
  KSA: "Saudi Arabia",
  SEN: "Senegal",
  SRB: "Serbia",
  SEY: "Seychelles",
  SLE: "Sierra Leone",
  SIN: "Singapore",
  SVK: "Slovakia",
  SLO: "Slovenia",
  SOL: "Solomon Islands",
  SOM: "Somalia",
  RSA: "South Africa",
  KOR: "South Korea",
  ESP: "Spain",
  SRI: "Sri Lanka",
  SUD: "Sudan",
  SUR: "Suriname",
  SWZ: "Swaziland",
  SWE: "Sweden",
  SUI: "Switzerland",
  SYR: "Syria",
  TPE: "Taiwan",
  TJK: "Tajikistan",
  TAN: "Tanzania",
  THA: "Thailand",
  TLS: "Timor-Leste",
  TOG: "Togo",
  TGA: "Tonga",
  TRI: "Trinidad and Tobago",
  TUN: "Tunisia",
  TUR: "Türkiye",
  TKM: "Turkmenistan",
  TUV: "Tuvalu",
  UGA: "Uganda",
  UKR: "Ukraine",
  UAE: "United Arab Emirates",
  GBR: "United Kingdom",
  USA: "United States",
  URU: "Uruguay",
  UZB: "Uzbekistan",
  VAN: "Vanuatu",
  VEN: "Venezuela",
  VIE: "Vietnam",
  ISV: "Virgin Islands",
  YEM: "Yemen",
  ZAM: "Zambia",
  ZIM: "Zimbabwe",
};
const CountryAlphaTwoList: {
  [countryCode in (typeof CountryList)[number]]: string;
} = {
  "": "",
  CAN: "ca",
  AFG: "af",
  ALB: "al",
  ALG: "dz",
  ASA: "as",
  AND: "ad",
  ANG: "ao",
  ANT: "ag",
  ARG: "ar",
  ARM: "am",
  ARU: "aw",
  AUS: "au",
  AUT: "at",
  AZE: "az",
  BAH: "bs",
  BRN: "bh",
  BAN: "bd",
  BAR: "bb",
  BLR: "by",
  BEL: "be",
  BIZ: "bz",
  BEN: "bj",
  BER: "bm",
  BHU: "bt",
  BOL: "bo",
  BIH: "ba",
  BOT: "bw",
  BRA: "br",
  IVB: "vg",
  BRU: "bn",
  BUL: "bg",
  BUR: "bf",
  BDI: "bi",
  CAM: "kh",
  CMR: "cm",
  CPV: "cv",
  CAY: "ky",
  CAF: "cf",
  CHA: "td",
  CHI: "cl",
  CHN: "cn",
  COL: "co",
  COM: "km",
  COK: "ck",
  CRC: "cr",
  CIV: "ci",
  CRO: "hr",
  CUB: "cu",
  CYP: "cy",
  CZE: "cz",
  COD: "cd",
  DEN: "dk",
  DJI: "dj",
  DMA: "dm",
  DOM: "do",
  ECU: "ec",
  EGY: "eg",
  ESA: "sv",
  GEQ: "gq",
  ERI: "er",
  EST: "ee",
  ETH: "et",
  FSM: "fm",
  FIJ: "fj",
  FIN: "fi",
  FRA: "fr",
  GAB: "ga",
  GAM: "gm",
  GEO: "ge",
  GER: "de",
  GHA: "gh",
  GRE: "gr",
  GRN: "gd",
  GUM: "gu",
  GUA: "gt",
  GUI: "gn",
  GBS: "gw",
  GUY: "gy",
  HAI: "ht",
  HON: "hn",
  HKG: "hk",
  HUN: "hu",
  ISL: "is",
  IND: "in",
  INA: "id",
  IRI: "ir",
  IRQ: "iq",
  IRL: "ie",
  ISR: "il",
  ITA: "it",
  JAM: "jm",
  JPN: "jp",
  JOR: "jo",
  KAZ: "kz",
  KEN: "ke",
  KIR: "ki",
  KUW: "kw",
  KGZ: "kg",
  LAO: "la",
  LAT: "lv",
  LIB: "lb",
  LES: "ls",
  LBR: "lr",
  LBA: "ly",
  LIE: "li",
  LTU: "lt",
  LUX: "lu",
  MKD: "mk",
  MAD: "mg",
  MAW: "mw",
  MAS: "my",
  MDV: "mv",
  MLI: "ml",
  MLT: "mt",
  MHL: "mh",
  MTN: "mr",
  MRI: "mu",
  MEX: "mx",
  MDA: "md",
  MON: "mc",
  MGL: "mn",
  MNE: "me",
  MAR: "ma",
  MOZ: "mz",
  MYA: "mm",
  NAM: "na",
  NRU: "nr",
  NEP: "np",
  NED: "nl",
  AHO: "an",
  NZL: "nz",
  NCA: "ni",
  NIG: "ne",
  NGR: "ng",
  PRK: "kp",
  NOR: "no",
  OMA: "om",
  PAK: "pk",
  PLW: "pw",
  PLE: "ps",
  PAN: "pa",
  PNG: "pg",
  PAR: "py",
  PER: "pe",
  PHI: "ph",
  POL: "pl",
  POR: "pt",
  PUR: "pr",
  QAT: "qa",
  CGO: "cg",
  ROM: "ro",
  RUS: "ru",
  RWA: "rw",
  SKN: "kn",
  LCA: "lc",
  VIN: "vc",
  SAM: "ws",
  SMR: "sm",
  STP: "st",
  KSA: "sa",
  SEN: "sn",
  SRB: "rs",
  SEY: "sc",
  SLE: "si",
  SIN: "sg",
  SVK: "sk",
  SLO: "si",
  SOL: "sb",
  SOM: "so",
  RSA: "za",
  KOR: "kr",
  ESP: "es",
  SRI: "lk",
  SUD: "sd",
  SUR: "sr",
  SWZ: "sz",
  SWE: "se",
  SUI: "ch",
  SYR: "sy",
  TPE: "tw",
  TJK: "tj",
  TAN: "tz",
  THA: "th",
  TLS: "tl",
  TOG: "tg",
  TGA: "to",
  TRI: "tt",
  TUN: "tn",
  TUR: "tr",
  TKM: "tm",
  TUV: "tv",
  UGA: "ug",
  UKR: "ua",
  UAE: "ae",
  GBR: "gb",
  USA: "us",
  URU: "uy",
  UZB: "uz",
  VAN: "vu",
  VEN: "ve",
  VIE: "vn",
  ISV: "vg",
  YEM: "ye",
  ZAM: "zm",
  ZIM: "zw",
};

export class Country {
  countryCode: (typeof CountryList)[number];
  constructor(countryCode: string) {
    if (CountryList.includes(countryCode as (typeof CountryList)[number]))
      this.countryCode = countryCode as (typeof CountryList)[number];
    else this.countryCode = "";
  }
  name() {
    return CountryNameList[this.countryCode];
  }
  toString() {
    return this.name() + (this.countryCode ? `(${this.countryCode})` : "");
  }
  alphaTwo() {
    return CountryAlphaTwoList[this.countryCode];
  }
}
